import type { Organization, User, CompanyAssignment, Invoice, Review, AuditLog } from "./types"

// Mock Organizations
export const mockOrganizations: Organization[] = [
  {
    _id: "org-platform",
    type: "platform",
    name: "FinShield Platform",
    status: "active",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "org-company-1",
    type: "company",
    name: "Acme Corporation",
    status: "active",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    _id: "org-company-2",
    type: "company",
    name: "TechStart Inc.",
    status: "active",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    _id: "org-company-3",
    type: "company",
    name: "Global Finance Ltd.",
    status: "active",
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-15"),
  },
]

// Mock Users
export const mockUsers: User[] = [
  // Platform Users
  {
    _id: "user-superadmin",
    orgId: "org-platform",
    portal: "admin",
    role: "SUPER_ADMIN",
    email: "admin@finshield.com",
    username: "superadmin",
    status: "active",
    mustChangePassword: false,
    lastLoginAt: new Date("2024-12-18"),
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "user-auditor-1",
    orgId: "org-platform",
    portal: "admin",
    role: "AUDITOR",
    email: "auditor1@finshield.com",
    username: "auditor1",
    status: "active",
    mustChangePassword: false,
    createdByUserId: "user-superadmin",
    lastLoginAt: new Date("2024-12-17"),
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    _id: "user-auditor-2",
    orgId: "org-platform",
    portal: "admin",
    role: "AUDITOR",
    email: "auditor2@finshield.com",
    username: "auditor2",
    status: "active",
    mustChangePassword: false,
    createdByUserId: "user-superadmin",
    lastLoginAt: new Date("2024-12-16"),
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    _id: "user-regulator-1",
    orgId: "org-platform",
    portal: "admin",
    role: "REGULATOR",
    email: "regulator@sec.gov.ph",
    username: "regulator1",
    status: "active",
    mustChangePassword: false,
    createdByUserId: "user-superadmin",
    lastLoginAt: new Date("2024-12-18"),
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  // Company Users - Acme Corporation
  {
    _id: "user-manager-1",
    orgId: "org-company-1",
    portal: "user",
    role: "COMPANY_MANAGER",
    email: "manager@acme.com",
    username: "acme_manager",
    status: "active",
    mustChangePassword: false,
    createdByUserId: "user-superadmin",
    lastLoginAt: new Date("2024-12-18"),
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    _id: "user-employee-1",
    orgId: "org-company-1",
    portal: "user",
    role: "COMPANY_USER",
    email: "john@acme.com",
    username: "john_doe",
    status: "active",
    mustChangePassword: false,
    createdByUserId: "user-manager-1",
    lastLoginAt: new Date("2024-12-17"),
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    _id: "user-employee-2",
    orgId: "org-company-1",
    portal: "user",
    role: "COMPANY_USER",
    email: "jane@acme.com",
    username: "jane_smith",
    status: "active",
    mustChangePassword: false,
    createdByUserId: "user-manager-1",
    lastLoginAt: new Date("2024-12-16"),
    createdAt: new Date("2024-02-25"),
    updatedAt: new Date("2024-02-25"),
  },
  {
    _id: "user-employee-3",
    orgId: "org-company-1",
    portal: "user",
    role: "COMPANY_USER",
    email: "disabled@acme.com",
    username: "disabled_user",
    status: "disabled",
    mustChangePassword: false,
    createdByUserId: "user-manager-1",
    disabledByUserId: "user-manager-1",
    disabledAt: new Date("2024-11-01"),
    disableReason: "Employee terminated",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-11-01"),
  },
  // Company Users - TechStart Inc.
  {
    _id: "user-manager-2",
    orgId: "org-company-2",
    portal: "user",
    role: "COMPANY_MANAGER",
    email: "manager@techstart.com",
    username: "techstart_manager",
    status: "active",
    mustChangePassword: false,
    createdByUserId: "user-superadmin",
    lastLoginAt: new Date("2024-12-15"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
]

// Mock Company Assignments
export const mockAssignments: CompanyAssignment[] = [
  {
    _id: "assign-1",
    companyOrgId: "org-company-1",
    auditorUserId: "user-auditor-1",
    status: "active",
    assignedByUserId: "user-superadmin",
    assignedAt: new Date("2024-02-15"),
    notes: "Primary auditor for Acme Corporation",
  },
  {
    _id: "assign-2",
    companyOrgId: "org-company-2",
    auditorUserId: "user-auditor-1",
    status: "active",
    assignedByUserId: "user-superadmin",
    assignedAt: new Date("2024-03-01"),
    notes: "Secondary assignment",
  },
  {
    _id: "assign-3",
    companyOrgId: "org-company-3",
    auditorUserId: "user-auditor-2",
    status: "active",
    assignedByUserId: "user-superadmin",
    assignedAt: new Date("2024-03-15"),
  },
]

// Mock Invoices
export const mockInvoices: Invoice[] = [
  {
    _id: "inv-001",
    companyOrgId: "org-company-1",
    uploadedByUserId: "user-employee-1",
    invoiceNo: "INV-2024-001",
    invoiceDate: new Date("2024-12-01"),
    totals_total: 15000.0,
    ai_verdict: "clean",
    ai_riskScore: 0.12,
    blockchain_txHash: "0x1234567890abcdef1234567890abcdef12345678",
    blockchain_anchoredAt: new Date("2024-12-01T10:30:00"),
    status: "verified",
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2024-12-02"),
    companyName: "Acme Corporation",
    uploadedByName: "John Doe",
  },
  {
    _id: "inv-002",
    companyOrgId: "org-company-1",
    uploadedByUserId: "user-employee-1",
    invoiceNo: "INV-2024-002",
    invoiceDate: new Date("2024-12-05"),
    totals_total: 8500.5,
    ai_verdict: "flagged",
    ai_riskScore: 0.78,
    blockchain_txHash: "0xabcdef1234567890abcdef1234567890abcdef12",
    blockchain_anchoredAt: new Date("2024-12-05T14:20:00"),
    status: "flagged",
    createdAt: new Date("2024-12-05"),
    updatedAt: new Date("2024-12-05"),
    companyName: "Acme Corporation",
    uploadedByName: "John Doe",
  },
  {
    _id: "inv-003",
    companyOrgId: "org-company-1",
    uploadedByUserId: "user-employee-2",
    invoiceNo: "INV-2024-003",
    invoiceDate: new Date("2024-12-10"),
    totals_total: 22500.0,
    ai_verdict: "clean",
    ai_riskScore: 0.05,
    blockchain_txHash: "0x567890abcdef1234567890abcdef1234567890ab",
    blockchain_anchoredAt: new Date("2024-12-10T09:15:00"),
    status: "pending",
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-10"),
    companyName: "Acme Corporation",
    uploadedByName: "Jane Smith",
  },
  {
    _id: "inv-004",
    companyOrgId: "org-company-1",
    uploadedByUserId: "user-employee-1",
    invoiceNo: "INV-2024-004",
    invoiceDate: new Date("2024-12-15"),
    totals_total: 5200.75,
    ai_verdict: "flagged",
    ai_riskScore: 0.92,
    status: "fraudulent",
    createdAt: new Date("2024-12-15"),
    updatedAt: new Date("2024-12-16"),
    companyName: "Acme Corporation",
    uploadedByName: "John Doe",
  },
  {
    _id: "inv-005",
    companyOrgId: "org-company-2",
    uploadedByUserId: "user-manager-2",
    invoiceNo: "TS-INV-001",
    invoiceDate: new Date("2024-12-08"),
    totals_total: 45000.0,
    ai_verdict: "clean",
    ai_riskScore: 0.08,
    blockchain_txHash: "0xcdef1234567890abcdef1234567890abcdef1234",
    blockchain_anchoredAt: new Date("2024-12-08T11:45:00"),
    status: "verified",
    createdAt: new Date("2024-12-08"),
    updatedAt: new Date("2024-12-09"),
    companyName: "TechStart Inc.",
    uploadedByName: "TechStart Manager",
  },
  {
    _id: "inv-006",
    companyOrgId: "org-company-2",
    uploadedByUserId: "user-manager-2",
    invoiceNo: "TS-INV-002",
    invoiceDate: new Date("2024-12-12"),
    totals_total: 12750.25,
    ai_verdict: "flagged",
    ai_riskScore: 0.65,
    status: "pending",
    createdAt: new Date("2024-12-12"),
    updatedAt: new Date("2024-12-12"),
    companyName: "TechStart Inc.",
    uploadedByName: "TechStart Manager",
  },
  {
    _id: "inv-007",
    companyOrgId: "org-company-3",
    uploadedByUserId: "user-manager-2",
    invoiceNo: "GF-2024-001",
    invoiceDate: new Date("2024-12-14"),
    totals_total: 87500.0,
    ai_verdict: "clean",
    ai_riskScore: 0.15,
    blockchain_txHash: "0x890abcdef1234567890abcdef1234567890abcde",
    blockchain_anchoredAt: new Date("2024-12-14T16:00:00"),
    status: "pending",
    createdAt: new Date("2024-12-14"),
    updatedAt: new Date("2024-12-14"),
    companyName: "Global Finance Ltd.",
    uploadedByName: "GF Manager",
  },
]

// Mock Reviews
export const mockReviews: Review[] = [
  {
    _id: "review-001",
    invoiceId: "inv-001",
    companyOrgId: "org-company-1",
    reviewedByUserId: "user-auditor-1",
    decision: "verified",
    notes: "All documentation verified. Invoice matches purchase order.",
    createdAt: new Date("2024-12-02"),
    reviewerName: "Auditor 1",
  },
  {
    _id: "review-002",
    invoiceId: "inv-004",
    companyOrgId: "org-company-1",
    reviewedByUserId: "user-auditor-1",
    decision: "fraudulent",
    notes: "Duplicate invoice detected. Vendor does not exist in records.",
    createdAt: new Date("2024-12-16"),
    reviewerName: "Auditor 1",
  },
  {
    _id: "review-003",
    invoiceId: "inv-005",
    companyOrgId: "org-company-2",
    reviewedByUserId: "user-auditor-1",
    decision: "verified",
    notes: "Verified with vendor. Transaction confirmed.",
    createdAt: new Date("2024-12-09"),
    reviewerName: "Auditor 1",
  },
]

// Mock Audit Logs
export const mockAuditLogs: AuditLog[] = [
  {
    _id: "log-001",
    actorUserId: "user-superadmin",
    actorOrgId: "org-platform",
    action: "CREATE_ORGANIZATION",
    entity_type: "organization",
    entity_id: "org-company-1",
    createdAt: new Date("2024-02-15T09:00:00"),
    actorName: "Super Admin",
    actorEmail: "admin@finshield.com",
  },
  {
    _id: "log-002",
    actorUserId: "user-superadmin",
    actorOrgId: "org-platform",
    action: "CREATE_USER",
    entity_type: "user",
    entity_id: "user-manager-1",
    createdAt: new Date("2024-02-15T09:30:00"),
    actorName: "Super Admin",
    actorEmail: "admin@finshield.com",
  },
  {
    _id: "log-003",
    actorUserId: "user-superadmin",
    actorOrgId: "org-platform",
    action: "ASSIGN_AUDITOR",
    entity_type: "assignment",
    entity_id: "assign-1",
    createdAt: new Date("2024-02-15T10:00:00"),
    actorName: "Super Admin",
    actorEmail: "admin@finshield.com",
  },
  {
    _id: "log-004",
    actorUserId: "user-employee-1",
    actorOrgId: "org-company-1",
    action: "UPLOAD_INVOICE",
    entity_type: "invoice",
    entity_id: "inv-001",
    createdAt: new Date("2024-12-01T10:00:00"),
    actorName: "John Doe",
    actorEmail: "john@acme.com",
  },
  {
    _id: "log-005",
    actorUserId: "user-auditor-1",
    actorOrgId: "org-platform",
    action: "REVIEW_INVOICE",
    entity_type: "review",
    entity_id: "review-001",
    createdAt: new Date("2024-12-02T14:00:00"),
    actorName: "Auditor 1",
    actorEmail: "auditor1@finshield.com",
  },
  {
    _id: "log-006",
    actorUserId: "user-manager-1",
    actorOrgId: "org-company-1",
    action: "DISABLE_USER",
    entity_type: "user",
    entity_id: "user-employee-3",
    createdAt: new Date("2024-11-01T15:00:00"),
    actorName: "Acme Manager",
    actorEmail: "manager@acme.com",
  },
  {
    _id: "log-007",
    actorUserId: "user-employee-1",
    actorOrgId: "org-company-1",
    action: "UPLOAD_INVOICE",
    entity_type: "invoice",
    entity_id: "inv-002",
    createdAt: new Date("2024-12-05T14:00:00"),
    actorName: "John Doe",
    actorEmail: "john@acme.com",
  },
  {
    _id: "log-008",
    actorUserId: "user-auditor-1",
    actorOrgId: "org-platform",
    action: "REVIEW_INVOICE",
    entity_type: "review",
    entity_id: "review-002",
    createdAt: new Date("2024-12-16T10:00:00"),
    actorName: "Auditor 1",
    actorEmail: "auditor1@finshield.com",
  },
  {
    _id: "log-009",
    actorUserId: "user-superadmin",
    actorOrgId: "org-platform",
    action: "LOGIN",
    entity_type: "user",
    entity_id: "user-superadmin",
    createdAt: new Date("2024-12-18T08:00:00"),
    actorName: "Super Admin",
    actorEmail: "admin@finshield.com",
  },
  {
    _id: "log-010",
    actorUserId: "user-regulator-1",
    actorOrgId: "org-platform",
    action: "VIEW_BLOCKCHAIN_LEDGER",
    entity_type: "invoice",
    entity_id: "inv-001",
    createdAt: new Date("2024-12-18T11:00:00"),
    actorName: "Regulator 1",
    actorEmail: "regulator@sec.gov.ph",
  },
]
